services:
  db:
    image: 36-webapp-postgres:latest
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        BASE_POSTGRES_IMAGE: ${POSTGRES_IMAGE:-postgres:16.12-alpine3.23}
    restart: unless-stopped
    mem_limit: 768m
    cpus: 1.00
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-webapp36}
      POSTGRES_USER: ${POSTGRES_USER:-webapp36}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-webapp36}
    ports:
      - "${POSTGRES_FORWARD_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-webapp36} -d ${POSTGRES_DB:-webapp36}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp36-api:
    image: 36-webapp-webapp36-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1024m
    cpus: 2.00
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: ${BACKEND_PORT:-8000}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-False}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,webapp36-api,webapp36-web}
      DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS:-http://localhost:8080}
      DATABASE_URL: postgresql://${POSTGRES_USER:-webapp36}:${POSTGRES_PASSWORD:-webapp36}@db:5432/${POSTGRES_DB:-webapp36}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-3}
      GUNICORN_THREADS: ${GUNICORN_THREADS:-2}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-120}
    ports:
      - "${BACKEND_FORWARD_PORT:-8000}:${BACKEND_PORT:-8000}"
    volumes:
      - django_media:/app/media
      - django_static:/app/staticfiles
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import os, urllib.request; p=os.getenv('PORT','8000'); u=f'http://127.0.0.1:{p}/robots.txt'; r=urllib.request.Request(u, headers={'X-Forwarded-Proto':'https'}); urllib.request.urlopen(r, timeout=2)",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  webapp36-web:
    image: 36-webapp-webapp36-web:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1.00
    depends_on:
      webapp36-api:
        condition: service_healthy
    ports:
      - "${FRONTEND_FORWARD_PORT:-8080}:80"

volumes:
  postgres_data:
  django_media:
  django_static:
