# Generated by Django 5.2.9 on 2026-01-07 13:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='birth date'),
        ),
    ]
