# Generated by Django 5.2.9 on 2026-02-13 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blog/posts/hero/')),
                ('hero_image_alt', models.CharField(blank=True, max_length=200)),
                ('content_blocks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='blog/posts/og/')),
                ('geo_city', models.CharField(blank=True, max_length=120)),
                ('geo_region', models.CharField(blank=True, max_length=120)),
                ('geo_country', models.CharField(default='IR', max_length=2)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
