# Generated by Django 5.2.9 on 2026-01-06 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('daily_rate', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Daily Rate')),
                ('hourly_rate', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Hourly Rate')),
                ('monthly_rate', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monthly Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Space Name')),
                ('zone', models.CharField(choices=[('LONG_TABLE', 'Communal Long Table'), ('DESK', 'Individual Desk'), ('PRIVATE_ROOM', 'Private Room'), ('MEETING_ROOM', 'Meeting Room')], max_length=20, verbose_name='Zone Type')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Capacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('grid_row', models.IntegerField(default=0, verbose_name='Grid Row')),
                ('grid_col', models.IntegerField(default=0, verbose_name='Grid Col')),
                ('pricing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cowork.pricingplan', verbose_name='Pricing Plan')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], max_length=10, verbose_name='Booking Type')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=10, verbose_name='Status')),
                ('price_charged', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Price Charged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cowork.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-start_time'],
            },
        ),
    ]
