# Generated by Django 5.2.9 on 2026-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_contact_for_price',
            field=models.BooleanField(default=False, verbose_name='Contact for Price'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='six_month_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='6-Month Rate'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='yearly_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Yearly Rate'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('SIX_MONTH', '6-Month'), ('YEARLY', 'Yearly')], max_length=15, verbose_name='Booking Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed (Paid)'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
