# Generated by Django 5.2.9 on 2026-01-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0003_booking_payment_token_booking_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Daily Rate'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Monthly Rate'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='six_month_rate',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='6-Month Rate'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='yearly_rate',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Yearly Rate'),
        ),
        migrations.AlterField(
            model_name='space',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cowork.pricingplan', verbose_name='Pricing Plan'),
        ),
    ]
