# Generated by Django 5.2.9 on 2026-01-07 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0004_alter_pricingplan_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='parent_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='cowork.space', verbose_name='Parent Table'),
        ),
        migrations.AlterField(
            model_name='space',
            name='zone',
            field=models.CharField(choices=[('LONG_TABLE', 'Communal Long Table'), ('DESK', 'Individual Desk'), ('SHARED_DESK', 'Shared Table (4-Seated)'), ('PRIVATE_ROOM', 'Private Room'), ('MEETING_ROOM', 'Meeting Room')], max_length=20, verbose_name='Zone Type'),
        ),
    ]
