# Generated by Django 5.2.9 on 2026-01-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0005_space_parent_table_alter_space_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='zone',
            field=models.CharField(choices=[('LONG_TABLE', 'Communal Long Table'), ('DESK', 'Individual Desk'), ('SHARED_DESK', 'Shared Table (4-Seated)'), ('PRIVATE_2', 'VIP Room (2-Person)'), ('PRIVATE_3', 'VIP Room (3-Person)'), ('MEETING_ROOM', 'Meeting Room')], max_length=20, verbose_name='Zone Type'),
        ),
    ]
