# Generated by Django 5.2.9 on 2026-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0006_alter_space_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateField(verbose_name='Start Time'),
        ),
    ]
