# Generated by Django 5.2.9 on 2026-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0007_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Settled At'),
        ),
    ]
