# Generated by Django 5.2.9 on 2026-01-07 13:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0008_booking_settled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=django_jalali.db.models.jDateField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='settled_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Settled At'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=django_jalali.db.models.jDateField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
