# Generated by Django 5.2.9 on 2026-01-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0009_alter_booking_created_at_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20, verbose_name='Status'),
        ),
    ]
