# Generated by Django 5.2.9 on 2026-01-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0010_space_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['zone', 'sort_order', 'name'], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AddField(
            model_name='space',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
    ]
