# Generated by Django 5.2.9 on 2026-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0011_alter_space_options_space_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='zone',
            field=models.CharField(choices=[('LONG_TABLE', 'میز اشتراکی طولانی'), ('DESK', 'میز شخصی (تکی)'), ('SHARED_DESK', 'میز اشتراکی (۴ نفره)'), ('PRIVATE_2', 'اتاق VIP (۲ نفره)'), ('PRIVATE_3', 'اتاق VIP (۳ نفره)'), ('MEETING_ROOM', 'اتاق جلسه')], max_length=20, verbose_name='Zone Type'),
        ),
    ]
