# Generated by Django 5.2.9 on 2026-01-27 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0012_alter_space_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'REFUNDED']), _negated=True), fields=('space', 'start_time', 'end_time'), name='unique_active_booking_slot'),
        ),
    ]
