# Generated by Django 5.2.9 on 2026-02-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0012_space_x_pos_space_y_pos_alter_space_zone'),
        ('cowork', '0013_booking_unique_active_booking_slot'),
    ]

    operations = [
    ]
