# Generated by Django 5.2.9 on 2026-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0014_merge_20260205_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending Approval'),
                    ('CONFIRMED', 'Confirmed'),
                    ('CANCELLED', 'Cancelled'),
                    ('REFUNDED', 'Refunded'),
                    ('COMPLETED', 'Completed'),
                ],
                default='PENDING',
                max_length=10,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='space',
            name='zone',
            field=models.CharField(
                choices=[
                    ('LONG_TABLE', 'سیت روزانه'),
                    ('DESK', 'میز شخصی (تکی)'),
                    ('SHARED_DESK', 'میز اشتراکی (۴ نفره)'),
                    ('PRIVATE_2', 'اتاق VIP (۲ نفره)'),
                    ('PRIVATE_3', 'اتاق VIP (۳ نفره)'),
                    ('MEETING_ROOM', 'اتاق جلسه'),
                ],
                max_length=20,
                verbose_name='Zone Type',
            ),
        ),
    ]
