# Generated by Django 5.2.9 on 2026-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafeorder_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeorder',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Token'),
        ),
        migrations.AddField(
            model_name='cafeorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
    ]
