# Generated by Django 5.2.9 on 2026-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_cafeorder_payment_token_cafeorder_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeorder',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Settled At'),
        ),
    ]
