# Generated by Django 5.2.9 on 2026-01-07 13:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_cafeorder_settled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeorder',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cafeorder',
            name='settled_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Settled At'),
        ),
        migrations.AlterField(
            model_name='cafeorder',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
